### ISSUE TITLE
Build Error in   KiteRequestHandler.java

### ISSUE THREAD

**Issue by anudeepsharma82** [zerodha/javakiteconnect#22]
line 242 :         RequestBody body = RequestBody.create(jsonArray.toString(), JSON);

It seems 1st parameter shall be 2nd and 2nd shall be first.

**Comment by kssujithcj** [comment]
I am not an expert in Kotlin, but order doesn't matter in the case of named parameters, right?
The source code in Kotlin is [here](https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/RequestBody.kt#L199)
In javakiteconnect, we are just importing from this package and using it as provided.
We use Java 8 and okhttp-4.4.0 on test setup and it seems fine. Can you elaborate more about your setup with the version numbers?

**Comment by kssujithcj** [comment]
You can refer to all dependency library details [here](https://github.com/zerodha/javakiteconnect/blob/master/pom.xml).

**Comment by anudeepsharma82** [comment]
thanks .
