### ISSUE TITLE
Incorrect margins are returned

### ISSUE THREAD

**Issue by anudeepsharma82** [zerodha/javakiteconnect#23]
public void getCombinedMarginCalculation() throws IOException, KiteException{
        List<MarginCalculationParams> params = new ArrayList<>();

        MarginCalculationParams param = new MarginCalculationParams();
        param.exchange = "NFO";
        param.tradingSymbol = "NIFTY21MAY15400PE";
        param.orderType = "MARKET";
        param.quantity = 75;
        param.product = "MIS";
        param.variety = "regular";
        param.transactionType = "SELL";
      // param.price = 141819;

        MarginCalculationParams param2 = new MarginCalculationParams();
        param2.exchange = "NFO";
        param2.tradingSymbol = "NIFTY21MAY14450PE";
        param2.orderType = "MARKET";
        param2.quantity = (int)(75*ImportantPosition.HEDGED_QTY_MULTIPLIER);
        param2.product = "MIS";
        param2.variety = "regular";
        param.transactionType = "BUY";
      //  param2.price = 300;

        params.add(param2);
        params.add(param);
        
        CombinedMarginData combinedMarginData = getKiteConnect().getCombinedMarginCalculation(params, true, false);
        System.out.println(combinedMarginData.initialMargin.total);
        System.out.println(combinedMarginData.finalMargin.total);
    }

I tried gettting margins using above function. It seems SELL  margins are wrongly computed. Kindly check.

**Comment by kssujithcj** [comment]
You can use this for javakiteconnect client-related issues.
For API-related issues, you can write on [Kite Connect forum](https://kite.trade/forum).

**Comment by kssujithcj** [comment]
Please elaborate on the issue with a response from Kite Connect. It would save a lot of time if all the information is provided properly while posting the query.

**Comment by anudeepsharma82** [comment]
The attached screenshot from kite basket shows final margin of
approximately 35090 Rs but api returns Rs 17103 . It seems api is returning
only total of premiums.

**Comment by kssujithcj** [comment]
Please write on [Kite Connect forum](https://kite.trade/forum), we will check and get back to you.

**Comment by puneetshanbhag** [comment]
@anudeepsharma82 
Can you please check your code again once, seems like you are overwriting the param object "transactionType" , while you are creating the param2 object (second object)

**param.transactionType = "BUY";**

**Comment by anudeepsharma82** [comment]
Thanks @puneetshanbhag !
