### ISSUE TITLE
Exponential representation of volumes in WebSocket API 

### ISSUE THREAD

**Issue by sagarverma1919** [zerodha/javakiteconnect#25]
{open=311.1, close=310.25, high=315.45, low=310.5, volume=1.8547441E7, lasttradedprice=312.85, change=0.8380338436744634, lasttradedquantity=200.0, volumetradedtoday=0.0, totalbuyquantity=0.0, totalsellquantity=0.0, tradetimestamp=1626421247000}

The volume as **_1.8547441E7_**  is represented in exponential format

For further information please go through the forum discussion page https://kite.trade/forum/discussion/10122/incorrect-volume-data-from-websockets#latest

**Comment by kssujithcj** [comment]
We will change the volume to `long` in the coming releases.

**Comment by kssujithcj** [comment]
This is done on the release 3.2.1
