### ISSUE TITLE
Need an example to get Historical Data

### ISSUE THREAD

**Issue by ashishtomer** [zerodha/javakiteconnect#42]
I am trying to get `15minute` and `60minute` data of Silver, Gold etc. My MCX commodity trading is enabled. I have been getting `InputException` which is very frustrating.

I tried finding an example, which I did find [here](https://github.com/zerodha/javakiteconnect/blob/3578135c530ec01e0be3807139b74f83bd64dbaf/sample/src/Examples.java#L466). In this example, I get the parse error related to date formatter and date string. Which means, the example in this repo is outdated. Could you please give latest example in the repo to fetch historical data by `minute`, `15minute` and `60minute`?

On my own machine I run my "Scala" code like this:

```
    val historicalDayData = kiteConnect.getHistoricalData(
      Date.valueOf("2023-10-29"),
      Date.valueOf("2023-11-28"),
      "65953543",
      "day",
      true,
      true
    )
```

When I fetch the `day` data, there is no error. However, in case of `15minute` and `60minute` I am getting `InputException` error.

**Comment by ashishtomer** [comment]
I was able to resolve the issue. It has something to do with oi and continuous values. When I called with continuous = false, it worked. Could someone please elaborate on the rules of calling the functions? At least mention in the function documentation.

**Comment by kunalbarchha** [comment]
Not working for me even with continuous false. In fact, the example itself is failing with InputException. Completely copy paste as per their official example on this repo.
